### ISSUE TITLE
2주차 학습 내용

### ISSUE THREAD

**Issue by hnyoojin** [hnyoojin/jsDivers#1]
### To-do
- [ ] JS 개인 기본 개념 공부 (-10/3)
- [ ] 백준 10문제 풀기 (-10/2)
    - [ ] 2557 Hello World
    - [ ] #2
    - [ ] 1001 A-B
    - [ ] 10998 AxB
    - [ ] 1008 A/B
    - [ ] 10869 사칙연산
    - [ ] 10926 ??!
    - [ ] 18108 1998년생인 내가 태국에서는 2541년생?!
    - [ ] 10430 나머지
    - [ ] 2588 곱셈
- [ ] PR 코드 리뷰 (-10/3)
---
### Repo 사용 규칙
1. 주차별 브랜치 (week2)를 기반으로 개인 브랜치 생성 (Yoojin)
2. 개인 브랜치에서 코드 작업 완료 후 PR
    a. (week2 <- Yoojin)
3. 팀원들이 올린 PR 확인 후 코드 리뷰 남겨주기
    a. PR -> file changed
![image](https://github.com/user-attachments/assets/fe6a8084-601c-4eda-9422-0ccd0cf57595)
b. 파란 `+` 버튼 누르고 Start a review
c. 오른쪽 상단의 Finish your review
